### ISSUE TITLE
[Feature Contribution]: Initial DevOps and github actions clean up

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#252]
### What happened?

This is both an issue and a new feature. 
It aims to address duplication in Github actions as well as bring consistency of approach.

## First the audit with initial thoughts:

- build-cli-dotnet: build everything and run all tests - remove if duplicated
- build-packages: major functionality as library (Cli + webapi) - package integration test to ensure the library is working under happy path conditions => maybe publically github package as Beta 
- build-webapi: build test validate and compare => generated swagger changes should be part of the repo/tracked so obvious as part of the PR
- codeQL-anamlysis: scheduled - security check - static analysis to check for vulnerabilities for updated dependencies
- dev_carbon-aware-api: build test deploy DEV to public api endpoint
- run-sdkCLI-githubaction: CI/CD carbon aware github action => use for CodeQL ACTION
- verify-azure-function-with-packages: function validate the packages / solution deploys correctly and can I request the endpoint successfully => merge with others (e.g. build-packages)

## Initial recommendation of first changes to address:

- [ ] Rename and merge where needed
- Separate into the following themes (main build actions):
- [ ] - PR build and integration tests
- [ ] - build (& deploy?) on PR merge
- [ ] - Validate dependencies and integration tests (cron - can we use the CI/CD pipeline for this?)

## Also (further topics to cover in github actions):
- create releases?
- highlight Swagger updates in release notes
- I am also keen to version the builds and make sure it surfaces on the swagger as a relevant build version so people know if things have changed or that they are simply looking at the right thing (hoping that can be used in the analytics)

Thank you @bderusha for your inputs
cc @vaughanknight @Willmish 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by danuw** [comment]
To be discussed on Tuesday morning...

**Comment by YaSuenag** [comment]
I hope following topics are implemented on GHA - they are accepted in [ADR-0011](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0011-cd-pipeline.md):

* Ship WebAPI container images from GitHub packages
* Ship client libraries which are supported by GitHub packages

I think they should be kicked on release-created event on GHA.

**Comment by danuw** [comment]
@YaSuenag , worth linking https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/149 here

**Comment by YaSuenag** [comment]
@danuw I think it is better to upload OpenAPI YAML because SDK user can implement their clients without WebAPI container.

In addition, it is also better to upload documents of client bindings. In case of Java, we can generate Javadoc (API document) from source code comments, and we can integrate generating process into build process.

In my personal Java project, I use GHA to generate both release binary and API documents, then they will be uploaded to GitHub packages and GitHub pages. I'm happy if it helps you. https://github.com/YaSuenag/ffmasm/blob/main/.github/workflows/release.yml#L26-L38

**Comment by YaSuenag** [comment]
Thank @danuw for sharing current progress! I have some comments:

* How to use in standalone solutions
    * Can we use "AnyCPU" for .Net library? I think it is prefer to single binary if we can.
    * Can we add workflow to publish WebAPI container to GitHub container registry? It relates to [ADR-0011](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0011-cd-pipeline.md).
* How to use with Hosted APIs
    * Client library for Java conforms with Maven.
    * Would they be uploaded to GitHub packages? They are mentioned in ADR-0011, and Java / JS libraries should be uploaded at least.

**Comment by danuw** [comment]
Hi @YaSuenag , the above is just work in progress. I think the idea was to help visually explain what the repo enables and what we may or may not cover (that part is not yes illustrated on those graphs)
These are mainly to support and summarise what we are aiming for and will need to document further.

Anyway below to answer your questions.

>Can we use "AnyCPU" for .Net library? I think it is prefer to single binary if we can.
yes (I assume this also relates to stated ADR right?)

>Can we add workflow to publish WebAPI container to GitHub container registry? It relates to [ADR-0011](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0011-cd-pipeline.md).
yes, do you have anything (documented steps) to test, so we use as first success criteria and covered scope please?

>How to use with Hosted APIs
I believe this would not necessarily cover at first but rather document further how to generate if needed (such as through videos etc...). Do you believe more documentation is needed and if yes where shall we start? - we can probably discuss this on Tuesday

Hope above helps... Let me know

**Comment by Willmish** [comment]
My suggestion is: To also add workflows for testing Code samples of those samples we can test - that way we will keep them up to date with `dev` branch and not realise when someone tries the CA SDK for the first time that the sample is actually broken. Current samples: https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/dev/samples

**Comment by Willmish** [comment]
> I hope following topics are implemented on GHA - they are accepted in [ADR-0011](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0011-cd-pipeline.md):
> 
>     * Ship WebAPI container images from GitHub packages
> 
>     * Ship client libraries which are supported by GitHub packages
> 
> 
> I think they should be kicked on release-created event on GHA.

Would you be willing to collaborate on this with @danuw , as I can see you originally proposed that ADR?

**Comment by YaSuenag** [comment]
> @YaSuenag Would you be willing to collaborate on this with @danuw , as I can see you originally proposed that ADR?

Sure, I'd like to collaborate on this!  
However I think #149 is needed at first because OpenAPI document is needed to build client libraries. So I will start to work after merging #149 .

**Comment by danuw** [comment]
Following conversation with @YaSuenag around client packages releases, following is a refined plan of actions

- [ ] 1- PR (submit new features) - https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/321
   - CLI and WebApp (Build, unit tests, container integration tests?)
- [ ] 2- Release: - New pre-release for dev or official release for main (builds, versions and publishes container) for each platform - Tracked with https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/326
   - [ ] 2-a Deploy - created a container that gets deployed (should be published to packages as well? - depends on config and secret) - https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/322
       - manual approval gate for official release / automated approval gate for pre-release
       - release to public API (pulls container, deploys to API)
   - [ ] 2-b Create release packages:
       - pulls container and create clients for each "supported" platform (JAVA, JS, dotnet via nuget, python via pypi, etc...)
      - set of (basic?) integration tests per platform and then publishes to "public package repositories" (e.g. nuget, pypi, npm, etc..) - tracking ticket  TODO
      - at first, all packages are pre-release (long term, element of official release once we have had enough testing/feedback)
- [ ] 3- Regular Verification: (nighty/daily CA jobs that run check to ensure everything works and CodeQL etc... vulnerabilities) - tracking ticket  TODO

**Comment by danuw** [comment]
Thank you for your time @YaSuenag.

What we discussed:
- Issue with github package visibility -> action on me (@danuw ) to create an issue and talk to @vaughanknight 
- issue with docker image not working on MacOS (silicon) -> action on @danuw to research and propose a fix
- Prioritising a public official release package (priority 1 for NTT) -> action on @YaSuenag to propose a new workflow for that
- Lower priority for libraries generation (workflow 2.b described above) -> action on @YaSuenag to update previous proposed changes to reflect latest repo updates (docker image now coming from GH packages)

**Comment by Willmish** [comment]
Update in #355 : this is collecting updates on devops side in repo, @danuw suggested @YaSuenag to open PR for flow buliding packages for Java and JavaScript libraries for the CA SDK Web API.

**Comment by Willmish** [comment]
Update in #369: @danuw to update with most up to date info, first cleanup and changes merged in, in #361

**Comment by Willmish** [comment]
#381 Related

**Comment by danuw** [comment]
Will need to refresh this. 

May be worth closing and creating a new one...
