### ISSUE TITLE
🎯 2023-01-23 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#258]
## Date
2023-01-23 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] ADR review: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/201
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues
- [x] `/locations` API review and discussions now it's live!

# PRs

# Issues
- [ ] Issues found by @Willmish that still have not been addressed, easy to pick up:
  - [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/181
  - [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/259

## Discussion 
- [ ]  Check in on last agenda's Action Items:
  - [ ] Vaughan to ensure PM is added into calls / channels 
  - [ ] Vaughan to follow up on ElectricityMap key
  - [ ] Vaughan to update contribution guide in Changelog branch (add bullet point to update changelog.md)
  - [x] @Willmish to add PR adding Agenda template for GH issues
  - [x] @danuw to further check if there is anything we can do about spamming on the public API (AppInsights)
  - [x] @vaughanknight @Willmish to review updated PR by @YaSuenag #149 #150
  - [x] @YaSuenag #150 fix merge conflicts
  - [x] @FabioTurati-NTT to add an ADR for adding new DataSource for ElectricityMaps-Free

## Action Items
- [ ] @danuw  @Willmish  @vaughanknight  to review #261 

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by FabioTurati-NTT** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by Willmish** [comment]
Locations API: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/239

**Comment by danuw** [comment]
TODO: Create an issue around looking into APIM

Symptoms:
- cannot manage failing callers
- throttling from callers
- communications to users (unregistered users so we do not know who to message)
- multiple published versions for people to have a bit of time to adapt (ramp down period for previous versions)

Current functionality that may be affected (and double check alternatives):
- swagger definition public

**Comment by danuw** [comment]
Also we covered DevOps approach.

More generally we should add this list to the agenda https://github.com/Green-Software-Foundation/carbon-aware-sdk/labels/for%20discussion (as well as process - do we remove the "for discussion" label once we have covered it so the list recycles refreshes for new meetings?)
