### ISSUE TITLE
🎯2023-03-07 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#314]
## Date
2023-03-07 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Discuss: DCO in GSF projects: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/309
- [x] Check if: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/230 finally closed
- [x] Discuss: PRs recently updated to 'Ready for Review' status
- [x] Discuss: Whether @bderusha can be a maintainer / code reviewer, and review MS PRs
- [x] Check in on action items from #307 
- [x] Discussion: What features, PRs should go into v1.1? [Release]: v1.1 offical release - contents discussion  #308
- [x] Review Pull Requests
  - [x] #261 
- [ ] Discuss: Roadmap planning
- [x] Check in on issues marked "for discussion": https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aissue+is%3Aopen+label%3A%22for+discussion%22
- [x] Discuss Issues

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] @FabioTurati-NTT to add feature request on filter feature
- [ ] @bderusha to modify https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/179 with comments on geolocation feature
- [ ] Current timeline: Release v1.1 next week #308 
- [ ] Discuss: Roadmap planning After 1.1 release #308
- [ ]  Check in on issues marked "for discussion": https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aissue+is%3Aopen+label%3A%22for+discussion%22
- [ ] Discuss: Accepting ADRs merged in as 'Proposed' to the repo: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0012-electricity-maps-free.md

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by FabioTurati-NTT** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by otsuyo** [comment]
Attended

**Comment by vaughanknight** [comment]
Vaughan to erach out to internal Microsoft stakeholder to check if they would be comfortable with edit priveleges to mark PR's ready for review.

**Comment by Willmish** [comment]
@bderusha Officially approved to Review all PRs - including Microsoft dev team PRs not coming from him :)
