### ISSUE TITLE
🎯 2023-03-21 Carbon Aware SDK Weekly Meeting Agenda 

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#323]
## Date
2023-03-21 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] #319 - Stale issues (6 months) and PRs (3 months) will now be marked as stale, and closed after 20 days of inactivity after that 
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [ ] Discuss Issues

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] @danuw To shorten stale period by 2 months for issues and change label to `stale`
- [ ] @FabioTurati-NTT to add feature request on filter feature
- [ ] @bderusha to modify https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/179 with comments on geolocation feature
- [ ] Current timeline: Release v1.1 next week #308 
- [ ] Discuss: Accepting ADRs merged in as 'Proposed' to the repo: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0012-electricity-maps-free.md @Willmish to open PR
- [ ] @vaughanknight to create new branch for testing workflows for #252 (@YaSuenag @danuw )
- [ ] @danuw : Devops: #252
- [ ] @vaughanknight to manually compare `swagger.yaml` as its moved in #149  (that's why its failing)
- [ ] @tmcclell to look into setting up CA SDK with the most recent changes from dev and to resurface previous issues encountered when polling data from the US region
- [ ] @FabioTurati-NTT to look into a possible issue with CLI running time
- [ ] @Willmish reopen #114 
- [ ] @Willmish to raise CODEOWNERS discussion
- [ ] Add CHANGELOG to dev @vaughanknight 

**Meeting attended by**

**Comment by vaughanknight** [comment]
I'd like ot discuss #310 as part of the PR's, but also motion to approve it.  We had this in the beginning but it was removed due to not being neede dearly on, would be nice to add it back in as it can help generate documentation/csv files for human reading also.

**Comment by vaughanknight** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by FabioTurati-NTT** [comment]
Attended

**Comment by nttDamien** [comment]
Attended
