### ISSUE TITLE
[Feature Contribution]: Roadmap to create releases (main and multi platform packages)

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#326]
### What happened?

As the Carbon Aware SDK project
I want to add workflows to create a release (for main and pre-release for dev) container
So that I publicly release a package of the latest changes for others to consume

The scope of this ticket is to:
- [ ] publish new package/container: create a new workflow that fits in plan described at https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/252 to create a release container to github packages - if source branch is dev it is -pre-release, if source branch is main it is official release. Workflow to be called `2-release.yaml`
- [ ] release strategy: confirm how we will proceed to implement our release strategy of versioning
- [ ] [update deployment](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/.github/workflows/dev_carbon-aware-api.yml) to [Azure public api](https://carbon-aware-api.azurewebsites.net/swagger/index.html) to implement release strategy using publicly available package
- [ ] Create client libraries for different platform (to be updated)
   - [ ] Java (maven)
   - [ ] JS (npm)
   - [ ] Python (pypi)
   - [ ] dotnet (nuget)
   - [ ] ...

This is related to parent https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/252

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by danuw** [comment]
Linking https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/336
