### ISSUE TITLE
🎯2023-04-25 Carbon Aware SDK Weekly Meeting Agenda 

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#337]
## Date
2023-04-25 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Discuss : Google Groups usage
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Look through the Action Points
- [x] Pick up back at: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/288 at the next meeting
- [x] V1.1 release planning: @vaughanknight to lead discussion
- [ ] Consider: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/179
- [ ] Discuss Issues

## Wednesday meeting Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Discuss : Google Groups usage
- [x] Approve Past Meeting Minutes
- [x] Pick up back at: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/288 at the next meeting
- [ ] Look through the Action Points
- [ ] V1.1 release planning: @vaughanknight to lead discussion
- [ ] Consider: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/179
- [ ] Review Pull Requests
- [ ] Discuss Issues
# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [x] @FabioTurati-NTT to add feature request on filter feature
- [x] @bderusha to modify https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/179 with comments on geolocation feature
- [x] Discuss: Accepting ADRs merged in as 'Proposed' to the repo: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0012-electricity-maps-free.md @Willmish to open PR
- [x] Add CHANGELOG to dev @vaughanknight 
- [x] @vaughanknight to manually compare `swagger.yaml` as its moved in #149  (that's why its failing)
- [ ] Current timeline: Release v1.1 next week #308 
- [ ] @vaughanknight to create new branch for testing workflows for #252 (@YaSuenag @danuw )
- [ ] @danuw : Devops: #252
- [ ] @tmcclell to look into setting up CA SDK with the most recent changes from dev and to resurface previous issues encountered when polling data from the US region
- [ ] @Willmish reopen #114 
- [ ] @Willmish to raise CODEOWNERS discussion
- [ ] @Willmish log or start with configurations docs changes to make them more intuitive see #325 
- [ ] @Willmish @vaughanknight @danuw - Bring a task list for v1.1 for next meetign
- [ ] @Willmish Create invite list for google groups

**Meeting attended by**

**Comment by nttDamien** [comment]
attended

**Comment by vaughanknight** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by otsuyo** [comment]
attended

**Comment by Willmish** [comment]
Waiting 1 more week for an update on ADR state from "Accepted" to "Proposed" in the PR #288

**Comment by Willmish** [comment]
#312 under review by @vaughanknight

**Comment by Willmish** [comment]
@Willmish to look at #294

**Comment by vaughanknight** [comment]
Quick one - @vaughanknight to manually compare swagger.yaml as its moved in https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/149 (that's why its failing) .. this is merged and we did review it, is there anything outstanding?

**Comment by bderusha** [comment]
Attended: Wednesday meeting

**Comment by FabioTurati-NTT** [comment]
Attended

**Comment by danuw** [comment]
Packages are now public for the repo and we should be able to create packages on merge but will monitor the next merges to dev

cc @YaSuenag

**Comment by Willmish** [comment]
Notes Wednesday meeting:
- ADR dynamic DataSource Registration @bderusha adding an issue for the feature request and mentioned a possibility of someone /team at MS contributing this feature
- What we need to consider: Tracking which ADRs that are accepted got implemented/and which might be missing (on example of ADR 14 and ADR 6 - ADR 6 already is accepted and mentions dynamic datasource registration and was not implemented)
- Mentioned by @bderusha : opening a new issue for discussion on the currently proposed ADRs sitting in the repo
- Possibly: reflect this in documentation 
- Suggestion: using "for discussion" tag for the weekly rundown of repo activitiy (email) @jawache 
- Suggestion: For synchronous meetings, surface issues for people to discuss asynchronously (e.g. bringing up "for discussion" issues during the call plus hosting an initial discussion on the call) - maybe add GH bot looking at newest issues to add to the agenda in a comment
-

**Comment by YaSuenag** [comment]
@helayoty README.md which you make changes mentions for AKS only. https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/df4a3c6c28bbdea144d455d3f79b1bed70566f4c/samples/helm-deploy/README.md

I think it is better to remove description for AKS from README.md. We can require that the user need to prepare Kubernetes cluster by themselves in this case.
