### ISSUE TITLE
🎯 2023-05-02 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#343]
## Date
2023-05-02 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/337
- [x] CHANGELOG discussion - https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/308
- [x] Start off discussion: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/179
- [ ] Review Pull Requests 
- [ ] Look at @YaSuenag PRs
- [ ] Discuss Issues

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [x] Review #337 Comments and move here as needed @Willmish 

**Meeting attended by**

**Comment by YaSuenag** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by Willmish** [comment]
Notes:
- CHANGELOG discussions: @YaSuenag mentioned adding in publishing Swagger specification 
- CHANGELOG - @danuw mentioned adding in the public packages
- CHANGELOG - Should we link out to ADRs to the CHANGELOG? E.g. on Adding EM free support, add a hyperlink to ADR 12 https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0012-electricity-maps-free.md
- Raised by @danuw : Documentation site https://green-software-foundation.github.io/carbon-aware-sdk/ out of date, consider rebuilding it.
- @YaSuenag mentioned a possible FEATURE CONTRIBUTiON adding dynamic datasource SWITCHING at runtime - e.g. polling from WattTime for one location, and from EM for another (@danuw mentioned maybe do it based on Fallback strategy/priority (if datasource 1 does not have the data for location A, only then call the fallback datasource 2)
