### ISSUE TITLE
🎯 2023-05-09 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#349]
## Date
2023-05-09 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] FYI: Improving onboarding process currently under discussion by Oversight Committee at GSF: https://github.com/Green-Software-Foundation/oc/discussions/11 (This relates to how we improve project meeting visability)
- [x] CHANGELOG discussion - #308 Should we link out to ADRs to the CHANGELOG?
- [x] DIscussion: Method for discussion on the currently proposed ADRs sitting in the repo
- [ ] issues raised for dicusssion:  Documentation site out of date: #344 , #345 ,  ADR 006 feat. contribution issue: #348
- [ ] Issues marked for discussion: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aopen+is%3Aissue+label%3A%22for+discussion%22
- [ ] Review Pull Requests
- [ ] Discuss Issues

## Agenda Wednesday
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes
- [x] Review the agenda and suggest new agenda points
- [x] FYI: Improving onboarding process currently under discussion by Oversight Committee at GSF: https://github.com/Green-Software-Foundation/oc/discussions/11 (This relates to how we improve project meeting visability)
- [x] CHANGELOG discussion - #308 Should we link out to ADRs to the CHANGELOG?
- [x] Carbon QL project update @bderusha 
- [x] ADR 14 implementation @bderusha 
- [x] DIscussion: Method for discussion on the currently proposed ADRs sitting in the repo
- [ ] issues raised for dicusssion:  Documentation site out of date: #344 , #345 ,  ADR 006 feat. contribution issue: #348
- [ ] Issues marked for discussion: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aopen+is%3Aissue+label%3A%22for+discussion%22
- [ ] Review Pull Requests
- [ ] Discuss Issues
# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/312 under review by @vaughanknight 
- [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/330 - being considered, currently test-json being the default for initial testing of the SDK is the desired behaviour @vaughanknight to contact PR owner
- [ ] @Willmish to look at https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/294
- [ ] @Willmish reopen [Sample]: Jupyter notebook Demo of web API  #114
- [ ] @Willmish Can we add this to the generic agenda template please? https://github.com/Green-Software-Foundation/carbon-aware-sdk/pulls?q=is%3Apr+is%3Aopen+label%3A%22for+discussion%22

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by danuw** [comment]
@Willmish  Can we add this to the generic agenda template please? https://github.com/Green-Software-Foundation/carbon-aware-sdk/pulls?q=is%3Apr+is%3Aopen+label%3A%22for+discussion%22

**Comment by tiwatsuka** [comment]
Attended

**Comment by otsuyo** [comment]
Attended

**Comment by vaughanknight** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by nttDamien** [comment]
attended

**Comment by Willmish** [comment]
Comments:
- @vaughanknight mentions having different sections in the CHANGELOG depending on the audiences (e.g. a section focusing more on the USER side vs DEV) - e.g. configuration file has changed
- Copilot X - waiting for access for repo to automate CHANGELOG tracking
- @danuw sent through a suggested CHANGELOG format: https://www.home-assistant.io/blog/2023/05/03/release-20235/
- RE ADR method for discussion: bring back opening discussion issues for Proposed ADRs and make final decisions on calls
-

**Comment by Willmish** [comment]
Attended Wednesday

**Comment by pritipath** [comment]
Attended Wednesday

**Comment by Willmish** [comment]
Notes from wednesday meeting:
- Raised by @bderusha : - Scope confusion of the CarbonQL project, is there an overlap with CA SDK, can they be consolidated?

**Comment by bderusha** [comment]
Discussed: https://github.com/Green-Software-Foundation/carbon-ql/issues/32

**Comment by danuw** [comment]
Attended Wednesday

**Comment by danuw** [comment]
Closing...
