### ISSUE TITLE
🎯 2023-05-15 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#354]
## Date
2023-05-16 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [ ] issues raised for dicusssion:  Documentation site out of date: #344 , #345 ,  ADR 006 feat. contribution issue: #348
- [ ] Issues marked for discussion: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aopen+is%3Aissue+label%3A%22for+discussion%22
- [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/312 under review by @vaughanknight 
- [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/330 - being considered, currently test-json being the default for initial testing of the SDK is the desired behaviour @vaughanknight to contact PR owner
- [ ] @Willmish to look at https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/294
- [ ] @Willmish reopen [Sample]: Jupyter notebook Demo of web API  #114
- [ ] @Willmish Can we add this to the generic agenda template please? https://github.com/Green-Software-Foundation/carbon-aware-sdk/pulls?q=is%3Apr+is%3Aopen+label%3A%22for+discussion%22
- [ ] Review Pull Requests
- [ ] Discuss Issues

## Agenda Wednesday
- [ ] Convene & Roll Call (5mins)
- [ ] Review Meeting Notices (see above)
- [ ] Approve Past Meeting Minutes
- [ ] Review the agenda and suggest new agenda points
- [ ] issues raised for dicusssion:  Documentation site out of date: #344 , #345 ,  ADR 006 feat. contribution issue: #348
- [ ] Issues marked for discussion: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aopen+is%3Aissue+label%3A%22for+discussion%22
- [ ] Review Pull Requests
- [ ] Discuss Issues
# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by otsuyo** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by danuw** [comment]
- [ ] from @nttDamien, more info on the roadmap from Vaughan
