### ISSUE TITLE
🎯 2023-09-12 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#392]
## Date
2023-09-12 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [ ] Issues marked for discussion: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aopen+is%3Aissue+label%3A%22for+discussion%22
- [ ] Discuss Issues

# PRs
- [x] https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/294
- [x] @YaSuenag wants #389 to be reviewed as soon as possible please.
- [x] #381 about helm charts
- [x] https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/375

# Issues 
- [x] @Willmish still chasing about Copilot PRs
- [x] https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/344 about documentation

## Discussion 
- [ ]  https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/386

## Action Items
- [ ] @vaughanknight , about #381, as per comments in the PR, do we (1) need to edit ADR, (2) do not need to edit the ADR, (3) edit the ADR separately ? Assuming (30 separate for now if we need to, but please confirm cc @YaSuenag 
- [ ] @Willmish to review #389 
- [ ] @Willmish to fix #383 (issue seems to be about removing dangling images when there are none which needs to be avoided)
- [ ] @danuw to progress #344 following latest feedback
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by Willmish** [comment]
Discussed:
- https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/381 and whether ADR 0004 needs to be modified - consensus - it doesnt have to be
- container_azure_function workflow breaking: https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions/runs/6155868045/job/16703465314

**Comment by Willmish** [comment]
Issue with the azure_function_workflow:
failing here: https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions/runs/6155868045/workflow#L32

Cause: `docker rmi -f $(docker images -f "dangling=true" -q)` , there are no dangling images at times so docker rmi -f fails as it needs at least one argument

Solution:
Add a check whether `docker images -f "dangling=true" -q` returns an empty list
