### ISSUE TITLE
🎯 2023-09-19 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#394]
## Date
2023-09-19 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
  - [x] #389 
  - [x] #393
  - [x] #381 
- [x] Discuss Issues
  - [x] Issues marked for discussion: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aopen+is%3Aissue+label%3A%22for+discussion%22

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] @vaughanknight , about #381, as per comments in the PR, do we (1) need to edit ADR, (2) do not need to edit the ADR, (3) edit the ADR separately ? Assuming (30 separate for now if we need to, but please confirm cc @YaSuenag 
- [x] @Willmish to review #389 
- [ ] @Willmish to fix #383 (issue seems to be about removing dangling images when there are none which needs to be avoided)
- [ ] @danuw to progress #344 following latest feedback
- [ ] next meeting: check status of #312 

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by Willmish** [comment]
Discussion points:
- When requesting from emisions endpoints "e.g. /emissions/bylocation", should we throw an [ArgumentOutOfRangeException](https://learn.microsoft.com/ja-jp/dotnet/api/system.argumentoutofrangeexception?view=net-7.0) exception when the dateRange is for example requesting a future date. 
@Willmish concern - we need to make assumptions about underlying data sources that they will not accept the date ranges.
