### ISSUE TITLE
🎯 2023-10-03 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#399]
## Date
2023-10-03 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
  - [x] #396 discussion
- [ ] https://github.com/orgs/Green-Software-Foundation/discussions/67
- [ ] CA SDK - will be undergoing review to officially be a "graduated" project under GSF https://oc.greensoftware.foundation/project-incubation-exit.html
- [ ] Review Pull Requests
  - [ ] #381 
  - [ ] #366 
  - [ ] Hanging:  #353 #340 #312
- [ ] Discuss Issues

# PRs

# Issues 

## Discussion 
- [ ]  https://github.com/orgs/Green-Software-Foundation/discussions/67

## Action Items
- [ ] ASK: Review discussion under #396 
- [ ] @vaughanknight , about #381, as per comments in the PR, do we (1) need to edit ADR, (2) do not need to edit the ADR, (3) edit the ADR separately ? Assuming (30 separate for now if we need to, but please confirm cc @YaSuenag 
- [ ] @danuw to progress #344 following latest feedback
- [ ] next meeting: check status of #312 
- [ ] #396 Action @vaughanknight DECISION: Create an ADR for this issue and discuss how we proceed
- [ ] @Willmish catchup with @bderusha : re: PR and ask on upgrading from .NET 6 to .NET 8
- [ ] @Willmish check with @seanmcilroy29 whether we can/is project meeting inviting automated via https://greensoftware.foundation/subscribe/ for CA SDK
- [ ] @tiwatsuka - open issue for upgrading the .NET version of CA SDK + explain the benefits for logging metrics/other

**Meeting attended by**

**Comment by Willmish** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by Willmish** [comment]
Unanswered question from #398:
https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/398#issuecomment-1735056961

**Comment by danuw** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended
