### ISSUE TITLE
2023-11-07 Carbon Aware SDK Weekly Meeting Agenda 🎯

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#408]
## Date
2023-11-7  - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Project Graduation - Sophie 
- [x] Review Pull Requests
  - [ ] #381 
  - [ ] #366 
  - [ ] Would be good to see if we can quickly approve #340 
  - [ ] #312
- [ ] Discuss Issues

# PRs

# Issues 

## Discussion 
- [ ]  https://github.com/orgs/Green-Software-Foundation/discussions/67
- [ ] We had a discussion around documentation for graduation of the CA SDK and the criteria - //CC @danuw this may be part of #344 - yasumasa mentioned it may help significantly 

## Action Items
- [ ] @Sophietn to share the criteria after initial approvals this week by oversight committee  
- [ ] Next release date targeted for ~Dec 12th to ensure we can release before the xmas break
- [ ] @vaughanknight to set up time with Bill to review the PR for ADR 006 #366 
- [ ] @ All : Flag issues and PRs that we would like to take into the next release to appear on the Carbon Aware SDK project board (see comments below for steps on how to if unclear)
- [ ] #312 to be rejected due to conflicts 

from previous meeting
- [ ] @danuw to progress #344 following latest feedback
- [ ] next meeting: check status of #312 
- [ ] @Willmish catchup with @bderusha : re: PR and ask on upgrading from .NET 6 to .NET 8
- [ ] @Willmish check with @seanmcilroy29 whether we can/is project meeting inviting automated via https://greensoftware.foundation/subscribe/ for CA SDK

**Meeting attended by**

**Comment by Sophietn** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by vaughanknight** [comment]
Attended
