### ISSUE TITLE
🎯  2023-11-21 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#417]
## Date
2023-11-21 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] GitHub Copilot 4 PRs
- [x] Graduation status - issues required for graduation
- [ ] Should https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/366 be in v1.2?
- [ ] Review Pull Requests
  - [ ] #381 
  - [ ] #366 
  - [ ] Would be good to see if we can quickly approve #340 
  - [ ] #312
  - [ ] Important to discuss: blocker for feature developed by @tiwatsuka : https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/404
- [ ] Discuss Issues

# PRs

# Issues 

## Discussion 
- [ ]  https://github.com/orgs/Green-Software-Foundation/discussions/67

## Action Items
- [ ] @Sophietn to follow up with @seanmcilroy29 - @Willmish CAN'T configure the copilotr4prs app, and its not working automatically on carbon aware sdk repo https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/418
- [ ] @vaughanknight : Check if he has access to configure Copilot4prs app for the CA SDK repo: https://github.com/apps/copilot4prs/
- [ ] #312 to be rejected due to conflicts 
- [ ] Next release date targeted for ~Dec 12th to ensure we can release before the xmas break
- [ ] @vaughanknight to set up time with Bill to review the PR for ADR 006 #366 
- [x] @ All : Flag issues and PRs that we would like to take into the next release to appear on the Carbon Aware SDK project board (see comments below for steps on how to if unclear)

from previous meeting
- [ ] @danuw to progress #344 following latest feedback
- [ ] next meeting: check status of #312 
- [ ] @Willmish check with @seanmcilroy29 whether we can/is project meeting inviting automated via https://greensoftware.foundation/subscribe/ for CA SDK

**Meeting attended by**

**Comment by Sophietn** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by Willmish** [comment]
Notes:
- GH Copilots 4PRs activated (thanks @Sophietn for chasing that up!) - @vaughanknight for your knowledge currently my gh account has access and there is a cost associated with it, so let's decide next week if we are happy with the output it produces and want to use it or not
