### ISSUE TITLE
🎯 2023-12-05 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#427]
## Date
2023-12-05 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues
  - [x] Should https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/366 be in v1.2?
  - [x] update to .net 8
  - [x] discuss about the timing to kick 5-publish-helm-chart.yaml to generate Chart OCI image

# PRs

- [x] Review Pull Requests
  - [x] #381 
  - [x] #366 
  - [x] Would be good to see if we can quickly approve #340 
  - [x] #312
  - [x] Important to discuss: blocker for feature developed by @tiwatsuka : https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/404

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] copilot4prs - can we get help from GitHub? @Sophietn to organise a call with @seanmcilroy29  and @vaughanknight and if no progress, organise a further one with GitHub...
- [x] @Sophietn to create agenda day before next meeting for people to start feeding back about point to cover in meeting - people subscribed at https://greensoftware.foundation/subscribe/ will be notified

from previous meeting
- [x] @Sophietn to follow up with @seanmcilroy29 - @Willmish CAN'T configure the copilotr4prs app, and its not working automatically on carbon aware sdk repo https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/418
- [x] @vaughanknight : Check if he has access to configure Copilot4prs app for the CA SDK repo: https://github.com/apps/copilot4prs/
- [x] #312 to be rejected due to conflicts 
- [x] Next release date targeted for ~Dec 12th to ensure we can release before the xmas break
- [x] @vaughanknight to set up time with Bill to review the PR for ADR 006 #366 
- [x] @danuw to progress #344 following latest feedback
- [x] next meeting: check status of #312 
- [x] @Willmish check with @seanmcilroy29 whether we can/is project meeting inviting automated via https://greensoftware.foundation/subscribe/ for CA SDK

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by Sophietn** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by Sophietn** [comment]
NOTES: 
.NET 8.0 #404  is still blocked, so removed from v1.2 (12th Dec release) and into v.next 
Migrating azure functions to isolated worker model #420  is part of the unblocker, also removed from v1.2 and into v.next 
Add example for podman play kube #340

**Comment by nttDamien** [comment]
Attended

**Comment by danuw** [comment]
- [ ] moved some issues to 1.3 as related to .net 8 (see comment from @Sophietn above)
- [ ] docusaurus update: wrking on the pipeline to get the site published to github pages (using the pipeline will help with samples doc as well). This will provide us with a beta version of the docs site people can feedback to be incorporated for graduation
- [ ] #366 @vaughanknight to look at
- [ ] copilot4prs - can we get help from GitHub? @Sophietn to organise a call with @seanmcilroy29  and @vaughanknight and if no progress, organise a further one with GitHub... now tracked through #429
  - [ ] aim to manually create the release notes - @danuw 
- [ ] @Sophietn to create agenda day before next meeting for people to start feeding back about point to cover in meeting - people subscribed at https://greensoftware.foundation/subscribe/ will be notified

**Comment by danuw** [comment]
FYI @YaSuenag https://github.com/Green-Software-Foundation/carbon-aware-sdk/pkgs/container/charts%2Fcarbon-aware-sdk

**Comment by Willmish** [comment]
- https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/340 pushed back to vNext
