### ISSUE TITLE
2024-01-09 Carbon Aware SDK Weekly Meeting Agenda 🎯

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#444]
## Date
2024-01-09 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Zoom call
Zoom meeting owner needs to update the meeting details

- [x] extend the meeting invites into 2024 
- [x] untick 'waiting room'
- [x]  tick Advanced options - 'Allow participants to join anytime' 
(so we can commence without the host). 

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve [Past Meeting Minutes](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/436)
- [x] **v1.2 Release status update**
PR raised from dev to main merge for v1.2 release, but codecov test failed.
[Bug Issue](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/438) to check the PR issues around code coverage raised - @vaughanknight ?

- [x] **Progress to Graduation**
Documentation update - same 3 issues still not assigned
Aim for 17th January meeting with OC > is this still achievable?

- [ ] Review Project Board 
- [ ] Review Pull Requests
- [ ] Review Issues

## Discussion 
- [ ]  Roadmap Planning

## Action Items
- [ ] Implement Data Source Registration per ADR-0006 #366 @vaughanknight to look at
- [ ]  @vaughanknight will review release PR issues BUG tomorrow 20th Dec
- [ ] merge release PR with @vaughanknight
- [ ] @vaughanknight to create the latest package release
- [ ] @Sophietn notify project meeting group and marketing team of new release
- [ ] Ensure we have a process for release notes (automation for next release since copilot4prs is not available to our project) - [GH Feature suggested here](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/433)

## AOB
Carbon Hack dates have changed. Now 18th of March until the 8th of April. Focussed on Impact Framework. 

**Meeting attended by**

**Comment by nttDamien** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by Sophietn** [comment]
Attended

**Comment by Sophietn** [comment]
I have granted @danuw with Admin permissions to work [docusauraus issue ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/344). Additional perms are required to configure security for Github pages (pipeline secrets)
