### ISSUE TITLE
🎯 2024-01-16 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#448]
## Date
2024-01-16 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
  - [x] Release PR #437 (also below)
  - [x] Progress to Graduation
          Aim for 17th January meeting with OC > is this still achievable?
          Use project board at https://github.com/orgs/Green-Software-Foundation/projects/15/views/2?filterQuery=label%3A%221.3%22
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
  - [x] #437 
  - [ ] #431 
  - [ ] #441 
  - [ ] #442 
- [ ] Discuss Issues
   - Closed issues
     - [ ] #447
   - New issues:
     - [ ] #446 
     - [ ] #445 
   - issues labeled as 1.2 to triage (obsolete? back to backlog? vnext?) 
    - [ ] https://github.com/orgs/Green-Software-Foundation/projects/15/views/2?filterQuery=label%3A%22v1.2%22

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items

(previous)
- [ ] Implement Data Source Registration per ADR-0006 #366 @vaughanknight to look at
- [x]  @vaughanknight will review release PR issues BUG tomorrow 20th Dec
- [x] merge release PR with @vaughanknight
- [ ] @vaughanknight to create the latest package release
- [x] @Sophietn notify project meeting group and marketing team of new release
- [ ] Ensure we have a process for release notes (automation for next release since copilot4prs is not available to our project) - [GH Feature suggested here](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/433)

**Meeting attended by**

**Comment by danuw** [comment]
Hi all, FYI I will be a few minutes late to the meeting (and as FYI, if I remember correctly, @Sophietn is off this week). Anyway, speak soon

**Comment by nttDamien** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by vaughanknight** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by pea-ms** [comment]
attended :)

**Comment by danuw** [comment]
- [ ] Now aiming for graduation on the 31st of Jan 2024
