### ISSUE TITLE
🎯2024-02-06 Carbon Aware SDK Meeting Agenda

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#458]
## Date
2024-02-06 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes
- [x] Review the agenda and suggest new agenda points

- [x]  v1.2 release retrospective 
15 minutes [Easyretro board ](https://easyretro.io/publicboard/4zmvc1GpYFWF5ukW7D1qusDa0sk2/6c13636b-74ca-4df7-ac33-1d7c424b0a32)

- [x] Progress to graduation
[Project board ](https://github.com/orgs/Green-Software-Foundation/projects/15/views/2?filterQuery=)
Target date 13th January 
What actions do we need to take now to ensure we're ready? 

- [x] Architectural Decision Recordhttps://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/455

- [x] Sync with IF (https://github.com/Green-Software-Foundation/opensource-wg/issues/97)

- [ ] Review Pull Requests

- [ ] Discuss Issues

## Action Items
- [ ] 

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by Sophietn** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by vaughanknight** [comment]
Vaughan catching up with NTT crew this week to discuss the ADR.

**Comment by vaughanknight** [comment]
Dan and Vaughan catching up on the Test Coverage documentation for graduation

**Comment by Sophietn** [comment]
**Actions** 

- [ ] @Willmish security.md https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/415 
- [ ] @danuw docusaurus https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/344#issuecomment-1916452552
- [ ] @vaughanknight readme https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/411
- [ ] @Sophietn update shortlink of docusaurus to mirror the IF one 
- [ ] @everyone to look at outstanding 1.3 issues ahead of graduation release

**Comment by Sophietn** [comment]
Notes from our [easy retro v1.2 release retrospective ](https://easyretro.io/publicboard/4zmvc1GpYFWF5ukW7D1qusDa0sk2/6c13636b-74ca-4df7-ac33-1d7c424b0a32)

Common themes
Went well - we had a release, worked well together, lots of contributors (9 individuals), new contributors from NTT was a great help 
To improve - we aimed to release on 12th Dec, we released 16th Jan, one month late, long delays waiting for automated release notes, surprise when we went to merge, hard to communicate with each other in between meetings

Actions 
- Let's set a release schedule of every month, whatever is ready (avoiding holiday periods like Christmas)
- Let's not use copilot4prs again - we're on a waitlist so this automation wasn't accessible to us, but it took us a while to work this out.We created a dependency on something else. We should take ownership of our own releases. Not rely elsewhere or wait unless critical.
- @Sophietn Set up a free calendar HOLD for release, 2nd Wednesday of every month. And 1 week previous HOLD to check everything is ready, release notes
- Use the mailing list to communicate, respond to the agenda email to ask to add on 30 mins before or after the weekly call if needed
