### ISSUE TITLE
🎯2024-02-13 Carbon Aware SDK Meeting Agenda

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#465]
## Date
2024-02-13 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes
- [x] Review the agenda and suggest new agenda points

- [ ] Progress to Graduation
[Project board ](https://github.com/orgs/Green-Software-Foundation/projects/15/views/2?filterQuery=)
Target date 13th January TODAY *edit 13th February
Update on [last week's actions](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/458#issuecomment-1929054040)
Review edits to Docusaurus

- [x] [Architectural Decision Record](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/455)

- [x] Update on [sync with IF, and UCL student team's work](https://github.com/Green-Software-Foundation/opensource-wg/issues/97)

- [ ] review OpenSSF Badge criteria: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/464#issuecomment-1939315165

- [ ] Review Pull Requests

- [ ] Discuss Issues

## Action Items
- [ ] 

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by Willmish** [comment]
Attended
Agenda suggestion:
- review OpenSSF Badge criteria: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/464#issuecomment-1939315165

**Comment by YaSuenag** [comment]
Attended

**Comment by devidayalhclteam** [comment]
Attended

**Comment by Willmish** [comment]
Adding a warning here: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/configuration.md#datasources

> Warning: Do not do this in production environment

or something like that

**Comment by danuw** [comment]
- [ ] Documentation PR review - can everyone have a look and leave a comment before the next meeting on whether they are happy with the new site and layout or if there are any particular concerns
  - [ ] @Sophietn - no outstanding tasks for graduation apart some reviews - we will let you know once ready, but we can probably start the process cc @vaughanknight 
- [ ] conversation between NTT data and @vaughanknight about prometheus - agreed way forward (.net 8 migration PRs first)
- [ ] quick replay of the interactions with IF team and UCL
- [ ] review OpenSSF Badge criteria: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/464#issuecomment-1939315165
  - [ ] for now we have 2 main concerns flagged with with warnings - We will address with following actions:
    - [ ] @Willmish add a comment to ensure we do not recommend storing secrets in app settings
    - [ ] Reenabling codecov tracked here https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/445
  - [ ] @Willmish to check what needs to happen to get the badge with @Sophietn

**Comment by Willmish** [comment]
@Sophietn just FYI as this is now merged (https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/464#issuecomment-1939315165), if we want to have a openSSF best practices badge this will need to be submitted for review here: https://www.bestpractices.dev/en/projects . But I guess this will have to be done by OC after their review?

**Comment by Sophietn** [comment]
> <img alt="image" width="210" src="https://private-user-images.githubusercontent.com/252951/304334989-100619c4-fa4e-471f-bbde-9ac10ee59a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MzcxNzcsIm5iZiI6MTcwNzgzNjg3NywicGF0aCI6Ii8yNTI5NTEvMzA0MzM0OTg5LTEwMDYxOWM0LWZhNGUtNDcxZi1iYmRlLTlhYzEwZWU1OWExZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxNTA3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDNmY2NkY2I3MTBkOGZjYmIzNGFmOTRlNjRjZDYyZjYxNWI2Nzc1MDdmMGRiMGUxNmE0NDRlMjZiZmM4ZTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-cvY2zc5fg2Zp_p27IrPNRcXaVI5atASbq3VuwaMIkA"> Assuming 13 Feb was the date?

@vaughanknight Yes typo sorry! Good to see we're on track for Graduating soon. Let me know once you're ready and we can prepare to raise an issue on the OC repo showcasing the project's fulfilment of the [Graduation acceptance criteria. ](https://oc.greensoftware.foundation/project-lifecycle.html#acceptance-criteria-2)


@Willmish Thanks again for your work to review us against the Open SSF Best Practice Badge. I've [added a comment on that PR](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/464#issuecomment-1941748513) so we save the effort you put in on our docs.
