### ISSUE TITLE
🎯 2024-03-12 Carbon Aware SDK Meeting Agenda 

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#488]
## Date
2024-03-12 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
  - [x] 1.3 release
  - [x] vNext release for .NET 8 upgrade?
  - [x] IF plug in
- [x] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs

Closed in the last week:
- [ ] #485 Docs overview, disclaimer & pipeline updates for graduation 
- [ ] #484 Release 1.3 - Graduation Release 
- [ ] #482 Fix regression during rebase in #421 
- [ ] #475 Release 1.3 changelog 
- [ ] #422 Add Prometheus exporter 
- [ ] #421 Add cache functionality for emissions data 
- [ ] #404 Upgrade to .NET 8.0 

Updated in the last week:
- [ ] #406 ADR Proposal: Throws exception when future datetime is passed to current/historical APIs 
- [x] #340 Add example for 'podman play kube'

# Issues 

Closed in the last week:
- [ ] #487 [Bug]: Getting started guide is lost 
- [ ] #477 [Bug]: Ensure the readme file shows as the project overview content on the documentation site 
- [ ] #474 Create release notes for 1.3 
- [ ] #439 [Bug]: lack of Linux support 
- [ ] #397 [Feature Contribution]: Data caching in the SDK

Updated in the last week:
- [x] #488 🎯 2024-03-12 Carbon Aware SDK Meeting Agenda  
- [ ] #486 [Bug]: Different times will return data with different structures. 
- [ ] #483 Release 1.3 - Graduation Release  
- [x] #481 🎯 2024-03-05 Carbon Aware SDK Meeting Agenda  
- [x] #473 🎯 2024-02-27 Carbon Aware SDK Meeting Agenda 
- [ ] #403 [Feature suggestion]: embrace a more holistic approach 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by JasonLuuk** [comment]
Sorry, I didn't realise about it maybe related to the time zone, I'm base in UK right not, GMT time, could you tell me how to add the time zone to the query statement if possible?
