### ISSUE TITLE
🎯 2024-03-19 Carbon Aware SDK Meeting Agenda

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#490]
## Date
2024-03-19 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
  - [x] vNext release for .NET 8 upgrade - what are the next steps towards .net 8 upgrade? any specific testing we are waiting on? and specific reviews? @YaSuenag's PR https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/489
  - [x] IF plug in - [repo](https://github.com/danuw/if-casdk-plugin)
- [x] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

## [PRs](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pulls)

PRs Updated:

- [ ] #489 Vnext/dotnet8 upgrade 
- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 
- [ ] #340 Add example for 'podman play kube' 

PRs Closed:

- [ ] #406 ADR Proposal: Throws exception when future datetime is passed to current/historical APIs 

## [Issues ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues)

Issues Closed:

- [ ] #481 🎯 2024-03-05 Carbon Aware SDK Meeting Agenda  
- [ ] #473 🎯 2024-02-27 Carbon Aware SDK Meeting Agenda 
- [ ] #439 [Bug]: lack of Linux support 
- [ ] #252 [Feature Contribution]: Initial DevOps and github actions clean up

Issues Updated:

- [ ] #490 🎯 2024-03-19 Carbon Aware SDK Meeting Agenda 
- [ ] #488 🎯 2024-03-12 Carbon Aware SDK Meeting Agenda  
- [ ] #486 [Bug]: Different times will return data with different structures. 
- [ ] #483 Release 1.3 - Graduation Release  
- [ ] #396 [Feature Contribution]: Better to throw exception when future datetime is specified to endpoints for current/historical data 
- [ ] #272 Feature request: Publish a versioned release as a NuGet package of the Carbon Aware SDK 

**Meeting attended by**

**Comment by tiwatsuka** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by devidayalhclteam** [comment]
Attended
