### ISSUE TITLE
🎯2024-03-26 Carbon Aware SDK Meeting Agenda

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#491]
## Date
2024-03-26 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

### Next Meeting 2nd April 
After UK Clock change. Should this call remain at 8am UTC (becoming 9am UK) or shift?
[Timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20240403T080000&p1=1440&p2=136&p3=107&p4=240&p5=248) on 2nd April for the majority of attendees 

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points 
- [x] Approve Past Meeting Minutes

- [x] We discussed our viewpoint on some arguments against CA, and agreed to add our conclusions in our documentation

- [x] **vNext release for .NET 8 upgrade** 
PR conflict will be resolved by @danuw 
Vaughan's happy with PR to approval merge once conflict is resolved 

- [ ] **IF plug in for the CA SDK** 
- [ ] **Roadmap for what's next ? - update to WattTime v3**

# PRs

# Issues 

Issues Updated:

- [ ] #491 🎯2024-03-26 Carbon Aware SDK Meeting Agenda 
- [x] #490 🎯 2024-03-19 Carbon Aware SDK Meeting Agenda PRs Closed

Issues Closed

- [ ] #488 🎯 2024-03-12 Carbon Aware SDK Meeting Agenda  
- [ ] #486 [Bug]: Different times will return data with different structures. 
- [ ] #483 Release 1.3 - Graduation Release

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by Sophietn** [comment]
Attended

**Comment by vaughanknight** [comment]
Attended
