### ISSUE TITLE
🎯 2024-04-16 Carbon Aware SDK Meeting Agenda 

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#499]
## Date
2024-04-16 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
       - [ ] v1.4 release for .NET 8 upgrade 
       @danuw will create the release notes this week, and send to @vaughanknight for review - this will include the .NET8 upgrade. **We shouldn't release until this v1.4 release will also adhere to all Graduation criteria quality.** 
      @danuw will double check we've achieved everything we need for the [.NET8 Milestone.](https://github.com/Green-Software-Foundation/carbon-aware-sdk/milestone/6?closed=1) Thank you NTT Data for the work. 
     @Sophietn will create an issue to make sure we've documented everything we did to get .NET8 working for the CA SDK - perhaps it could be an article/blog written by NTT data. 
      We'll need to publish a new Helm chart (probably don't need to wait for this - not breaking the release - but we can link to it retrospectively). @YaSuenag will create an issue for this work. 
       - [ ] IF plug in for the CA SDK
     @danuw we've created a plug-in that can be used as part of the IF - with an action for how it would work if it was merged into the IF. There's still a bit of cleanup to do for scheduling. Currently the plug in is housed on @danuw's repo.  We'll add this to the IF plug-in hub once it's live. It should require very little maintenance from us, but the accountability sits with us. 
    @Sophietn create issues for - IF plug-in documentation, -finalising final release of the plu-in, -moving the plug-in to the IF hub, -decide where to house 
    The missing part for scaling adoption is providing credentials to the providers (electricity maps, watt time). How can we solve this? Easily pass credentials in the header? Or published version has no credentials? Or credentials are overwritten? 
       - [ ] Graduation article - push for public adopters
       @NAMRATA-WOKE asked will individuals who would like to use the SDK still have access to data providers - electricity maps/watt time - individuals need to have their own accounts with these providers. There are free account options but the data provided is limited. Could we advise member orgs speak to electricity map/watt time to set up an account or see what free options would be available to them, ask for a temporary key to set up and trial. NTT's thoughts - internal process to pay for the accounts was fine, they enjoyed establishing a relationship with electricity map/watt time to be able to raise feature requests directly etc. 
      @Sophietn update the article to cover set up and selecting a data source.
       - [ ] Update to WattTime v3
       @danuw shared that in June the current version will no longer be supported. We need to *update the end points so the end points are connected to v3 and *ensure the new functionality in v3 works for our SDK. 
        https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/443 

# PRs

PRs Updated:

- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 
- [ ] #340 Add example for 'podman play kube' 

PRs Closed:

- [ ] #498 [URGENT] WebAPI container has not built due to segmentation fault 
- [ ] #497 Update agenda-template.md 
- [ ] #494 Fix typos

# Issues 

Issues Updated:

- [ ] #499 🎯 2024-04-16 Carbon Aware SDK Meeting Agenda  
- [ ] #495 🎯2024-04-09 Carbon Aware SDK Meeting Agenda 

Issues Closed:

- [ ] #496 [URGENT] WebAPI container has not built due to segmentation fault 
- [ ] #419 [Feature Contribution]: Migrate sample implementation of Azure Function to isolated worker model 
- [ ] #401 [Feature Contribution]: Upgrade .NET version to .NET 8

## Discussion 
- [ ]  

## Action Items
- [ ] @danuw release notes v1.4
- [x] @Sophietn create issues for .NET8blog, IF plug-in
- [x] @Sophietn update the Graduation article to cover set up and selecting a data source.
- [x] @YaSuenag create PR for Helmchart 

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by danuw** [comment]
Quick note to remind you that I won't be able to attend the next 2 meetings (23rd and 30th). Available most other days though if you need to get in touch.
Have a good week

**Comment by YaSuenag** [comment]
> We'll need to publish a new Helm chart (probably don't need to wait for this - not breaking the release - but we can link to it retrospectively). @YaSuenag will create an issue for this work.

I've sent PR #500 for this. I hope this will be merged and will published new Helm chart after v1.4 release.

**Comment by Sophietn** [comment]
Attended

Actions complete
- #501

**Comment by nttDamien** [comment]
[celebrate]     RDH ＲＯＵＸ Ｄａｍｉｅｎ/Roux, Damien (... reacted to your message:
________________________________
