### ISSUE TITLE
🎯2024-05-14 Carbon Aware SDK Weekly Meeting

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#517]
## Date
2024-05-14 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes

- [ ] v1.4 release
     - [x] https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/516 
     - [x]  #511 

- [ ]  Watt time v3
     - [x] Urgent actions https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/443#issuecomment-2071633432

- [x] .NET8 article review needed @vaughanknight @danuw https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/501#issuecomment-2100020004

- [ ] IF Plugin update @danuw #502 

# PRs

- review needed https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/515

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] feature suggestion : named regions and multiple configurations - (ability to create more mapping configurations and sepcifying the mapping configuration in the request) - create issues for this

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by Sophietn** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by danuw** [comment]
- [ ] merge conflicts to create the release 1.4 PR - @vaughanknight to check
 - [ ] watttime v3 - documentation done into 2 categories. Changes to the SDK to be priority 
 - [ ] @YaSuenag to create PR for this #501  to go into a blog post
 - [ ] no update on the impact framework yet, will resume after 1.4 and watttime v3 updates

**Comment by danuw** [comment]
Draft Release ready for @vaughanknight at https://github.com/Green-Software-Foundation/carbon-aware-sdk/releases/tag/untagged-bc7909c3afa03a0da900
