### ISSUE TITLE
🎯2024-05-21 Carbon Aware SDK Weekly Meeting

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#526]
## Date
2024-05-21 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes

- [ ]  Watt time v3
     - [x] Urgent actions https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/443#issuecomment-2071633432

- [x] .NET8 article review needed @vaughanknight @danuw https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/501#issuecomment-2100020004

- [x] OSWG Question: #525 

- [x] IF Plugin update @danuw #502 
We've had an if user request access to this so can we make it publicly accessible please? 

- [x] Add your thoughts! https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/521

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
PRs Updated:

- [ ] #524 Add blog article for .NET 8 upgrade 
- [ ] #523 documentation-change.yml: Created issue template for documentation ch… 
- [ ] #450 Remove JSON examples from artifacts 
- [ ] #366 Implement Data Source Registration per ADR-0006 

Issues Updated:

- [ ] #526 🎯2024-05-21 Carbon Aware SDK Weekly Meeting 
- [ ] #525 Define our 'value add' in our documentation 
- [ ] #520 [Bug]: Clean up DCO issues  
- [ ] #517 🎯2024-05-14 Carbon Aware SDK Weekly Meeting 
- [ ] #501 .NET8 blog article 
- [ ] #446 [Bug]: Address Security alerts 
- [ ] #443 [Feature Contribution]: Add support for WattTime v3 - latest version of the API with new features and coverage 

PRs Closed

- [ ] #522 Remove Hack mention from the Docs's banner 
- [ ] #518 Release 1.4 ( .net 8 upgrade) 
- [ ] #516 Update published documentation to .NET 8 
- [ ] #515 overview.md: Fixed three broken links 

Issues Closed

- [ ] #519 Remove hackathon sentence from our website banner 
- [ ] #514 2024-05-07 Carbon Aware SDK Weekly Meeting 🎯 
- [ ] #512 [Bug]: Broken links in overview.md file 
- [ ] #506 Check our published documentation to identify any references to .NET7 
- [ ] #395 [Action] Regular OSS WG Update %

**Comment by danuw** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by Sophietn** [comment]
Attended

**Comment by danuw** [comment]
- [ ] V3 WattTime upgrade progressing (@vaughanknight could not attend today but passed that on) #443 
- [ ] blog review about upgrade #501  - to review and once published on the SDK Docs blog, to be considered to republish on the GSF Articles blog. @danuw @vaughanknight 
- [ ] add value: team to comment with suggested wording on how they explain or summarise the advantages of using the SDK so we can better our docs/introduction - see https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/521
   - [ ] to be shared with our SDK subscribers too to reiterate on the advantages to leverage the SDK @Sophietn 
- [ ] IF SDK plug in - responding to direct request on initial plug in available at https://github.com/danuw/if-casdk-plugin - plans to better documentation after #443 is done
- [ ] #450 to review based on convo in #440
