### ISSUE TITLE
🎯2024-05-28 Carbon Aware SDK Weekly Meeting 

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#527]
## Date
2024-05-28 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Review Past Meeting Actions: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/526#issuecomment-2121966580

- [x]  Watt time v3

- [x] .NET8 article review needed @vaughanknight @danuw 

- [x] OSWG Question: #525 

- [x] IF Plugin update @danuw #502 

- [x] [Call for Features ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/521
) - request this is shared on LinkedIn @Sophietn 

# PRs

PRs Updated:

- [ ] #524 Add blog article for .NET 8 upgrade 
- [ ] #450 Remove JSON examples from artifacts 

# Issues 

Update adopters.md to add Microsoft https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/508 

Issues Updated:

- [ ] #527 🎯2024-05-28 Carbon Aware SDK Weekly Meeting  
- [ ] #526 🎯2024-05-21 Carbon Aware SDK Weekly Meeting 
- [ ] #525 Define our 'value add' in our documentation 
- [ ] #429 [Feature Contribution]: Enable Copilot4PRs 
- [ ] #348 [Feature Contribution]: Implement Data Source Registration per ADR-0006 
- [x] #262 [Feature Contribution]: Publish the docker file in a docker registry PRs Closed

Issues Closed

- [ ] #517 🎯2024-05-14 Carbon Aware SDK Weekly Meeting 
- [ ] #395 [Action] Regular OSS WG Update %                                             

## Discussion 
- [ ]  

## Action Items
- [ ] @danuw to chase @vaughanknight re. watttime v3 so we can get access to the changes to start testing asap.

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by Sophietn** [comment]
Attended
