### ISSUE TITLE
🎯 2024-06-04 Carbon Aware SDK Weekly Meeting

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#529]
## Date
2024-06-04 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [ ] Convene & Roll Call (5mins)
- [ ] Review Meeting Notices (see above)
- [ ] Review the agenda and suggest new agenda points
- [ ] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

- [ ]  Watt time v3
- [ ] .NET8 article review needed @vaughanknight @danuw 
- [ ] OSWG Question: #525 
- [ ] IF Plugin update @danuw #502 
- [ ] [Call for Features ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/521
) - request this is shared on LinkedIn @Sophietn 

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by vaughanknight** [comment]
Attended

**Comment by danuw** [comment]
Cover #340 and #471

**Comment by nttDamien** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by danuw** [comment]
- [ ] WattTime v3 updates expected next week @vaughanknight  #510 - code updates coming first and then some docs updates on highlighting main changes
   - [ ] we should try and hold off major changes
- [ ] #501 needs review @vaughanknight @danuw 
- [ ] #525 - @Sophietn any updates on this? 
   - [ ] @vaughanknight  brought up some points: are we sure this is what we need to focus on? 
- [ ] #521 - @vaughanknight and others to try and share with whom they know are using the SDK as a chance to help influence more relevant scenario aligned to their priorities
- [ ] PR:
   - [ ] #340 - pending evidence it works on a different machine (system test) - @YaSuenag 
   - [ ] #471 - giving the latest changes a week for comments - overall this generally improves efficiency of workflow to detect for changes to create a new container and launches new client generations too + this is sample that @YaSuenag will use, so we can iterate as we get new feedback
