### ISSUE TITLE
🎯2024-06-11 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#530]
## Date
2024-06-11 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues
- [x]  Watt time v3
- [x] .NET8 article review needed @vaughanknight @danuw 
- [ ] IF Plugin update @danuw #502 
- [ ] [Call for Features ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/521
) - request this is shared on LinkedIn @Sophietn 

- [x] OSWG Question: #525 

# PRs

PRs Updated:

- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 
- #340 was merged to `dev`

# Issues 

Issues Updated:
- Discussed #528 and that it would probably need an ADR just to make sure we're covering off all the right aspects of dynamic configuration loading and not overlooking anything.
- [ ] #529 🎯 2024-06-04 Carbon Aware SDK Weekly Meeting 
- [ ] #527 🎯2024-05-28 Carbon Aware SDK Weekly Meeting  
- [ ] #525 Define our 'value add' in our documentation 
- [ ] #502 Finalise Impact Framework Plug-In 
- [ ] #426 [Bug]: Unhandled exception. CarbonAware.Exceptions.ConfigurationException: No data sources are configured 

Issues Closed

- [ ] #526 🎯2024-05-21 Carbon Aware SDK Weekly Meeting 
- [ ] #262 [Feature Contribution]: Publish the docker file in a docker registry     

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by vaughanknight** [comment]
@danuw - just a reminder to review the .net 8 blog post please.
