### ISSUE TITLE
🎯 2024-06-18 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#533]
## Date
2024-06-18 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve [Past Meeting Minutes](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/530)
- [x] Watt time v3 - [watttime branch ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/wattime-v3-support)
@vaughanknight is working on it, and has raised a PR in the wattime branch. One test is failing. But it should be fixed and all changes merged in the next 24hours. Henry has been notified. Once deployed, it'd be good for everyone in the team to run the tests locally. 
- [x] .NET8 article review needed @vaughanknight @danuw - both will look at this and provide feedback this week. 
- [x] IF Plugin update @danuw #502 
- [x] [Call for Features ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/521) 
- [x] OSWG Question: #525 

# PRs

PRs Updated:

- [ ] #532 Watt Time v3 Support  
- [x] #531 Add configuration for tracing log 
- [ ] #524 Add blog article for .NET 8 upgrade 
- [ ] #523 documentation-change.yml: Created issue template for documentation ch… 
- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 
- [ ] #450 Remove JSON examples from artifacts 
- [ ] #366 Implement Data Source Registration per ADR-0006 

Closed:
- [ ] #522 Remove Hack mention from the Docs's banner 
- [ ] #518 Release 1.4 ( .net 8 upgrade) 
- [ ] #516 Update published documentation to .NET 8 
- [ ] #515 overview.md: Fixed three broken links Signed-off-by: joecus1 <joecusa… 
- [ ] #340 Add example for 'podman play kube' Issues Closed

# Issues 

Issues Updated:

- [ ] #533 🎯 2024-06-18 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #530 🎯2024-06-11 Carbon Aware SDK Weekly Meeting Agenda 
- [x] #528 [Bug]: Avoid inotify limit in WebAPI container on Kubernetes 
- [ ] #525 Define our 'value add' in our documentation 
- [ ] #520 [Bug]: Clean up DCO issues  
- [ ] #502 Finalise Impact Framework Plug-In 
- [ ] #501 .NET8 blog article 
- [ ] #443 [Feature Contribution]: Add support for WattTime v3 - latest version of the API with new features and coverage 
- [ ] #426 [Bug]: Unhandled exception. CarbonAware.Exceptions.ConfigurationException: No data sources are configured 
- [ ] #348 [Feature Contribution]: Implement Data Source Registration per ADR-0006 PRs Closed

Closed:
- [ ] #529 🎯 2024-06-04 Carbon Aware SDK Weekly Meeting 
- [ ] #527 🎯2024-05-28 Carbon Aware SDK Weekly Meeting  
- [ ] #526 🎯2024-05-21 Carbon Aware SDK Weekly Meeting 
- [ ] #519 Remove hackathon sentence from our website banner 
- [ ] #517 🎯2024-05-14 Carbon Aware SDK Weekly Meeting 
- [ ] #514 2024-05-07 Carbon Aware SDK Weekly Meeting 🎯 
- [ ] #512 [Bug]: Broken links in overview.md file 
- [ ] #506 Check our published documentation to identify any references to .NET7 
- [ ] #446 [Bug]: Address Security alerts 
- [ ] #429 [Feature Contribution]: Enable Copilot4PRs 
- [ ] #395 [Action] Regular OSS WG Update 
- [ ] #262 [Feature Contribution]: Publish the docker file in a docker registry %    

## Discussion 
- [ ]  

## Action Items
- [ ] #531 @vaughanknight to review. 
- [ ] #528 @vaughanknight to review. 

**Meeting attended by**

**Comment by Sophietn** [comment]
Attended

**Comment by Willmish** [comment]
Attended! :)

**Comment by YaSuenag** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended
