### ISSUE TITLE
🎯2024-07-02 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#537]
## Date
2024-07-02 - 7am UTC

## Meeting notices
Sophie's last meeting. Thanks for everything!
@russelltrow will be your new point of contact with the GSF. 

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Watt time v3 - merged into dev. #532 
- [x] .NET8 article review needed @vaughanknight @danuw
- [x] IF Plugin update @danuw #502 
- [x] [Call for Features ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/521) 
- [x] OSWG Question: #525 

# PRs

PRs Updated:

- [ ] #536 Updated azure-regions.json with new regions 
- [ ] #531 Add configuration for tracing log 
- [ ] #524 Add blog article for .NET 8 upgrade 
- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 

 PRs Closed

- [ ] #532 Watt Time v3 Support  
- [ ] #340 Add example for 'podman play kube' Issues Closed

# Issues 

Issues Updated:

- [ ] #537 🎯2024-07-02 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #535 [Bug]: Configuration for locations loads twice  
- [ ] #534 🎯2024-06-25 Carbon Aware SDK Weekly Meeting Agenda  
- [ ] #528 [Bug]: Avoid inotify limit in WebAPI container on Kubernetes 
- [ ] #525 Define our 'value add' in our documentation 
- [ ] #502 Finalise Impact Framework Plug-In 
- [ ] #476 [Feature Contribution]: Automatically remove "Ready for review" label on closed PRs or Issues 
- [ ] #455 ADR for Prometheus Metrics end point 
- [ ] #446 [Bug]: Address Security alerts 
- [ ] #426 [Bug]: Unhandled exception. CarbonAware.Exceptions.ConfigurationException: No data sources are configured

Issues Closed:

- [ ] #533 🎯 2024-06-18 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #530 🎯2024-06-11 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #529 🎯 2024-06-04 Carbon Aware SDK Weekly Meeting 
- [ ] #527 🎯2024-05-28 Carbon Aware SDK Weekly Meeting  
- [ ] #526 🎯2024-05-21 Carbon Aware SDK Weekly Meeting 
- [ ] #429 [Feature Contribution]: Enable Copilot4PRs 
- [ ] #262 [Feature Contribution]: Publish the docker file in a docker registry 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by Sophietn** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by danuw** [comment]
- [ ] create PR into main for release 1.5
    - [ ] update release notes if needed
 - [ ] as @Sophietn is leaving, who should help move the .net 8 upgrade blog post update to the GSF website - @nttDamien to talk to @NAMRATA-WOKE about the blog post
 - [ ] Call for features - let's plan what is next
    - [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/366
 - [ ] open issues and PRs - please do feel free to bug people to help move things forward - cc @YaSuenag I know you have a few things open
