### ISSUE TITLE
🎯 2024-07-09 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#539]
## Date
2024-07-09 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues:
 - [ ] #538 
 - [ ] #501 
 - [ ] Call for features - let's plan what is next
    - [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/366
 - [ ] open issues and PRs - please do feel free to bug people to help move things forward - cc @YaSuenag I know you have a few things open

# PRs

- [ ] #538 1.5 Release WattTime v3  
- [ ] #523 documentation-change.yml: Created issue template for documentation ch… 

- [ ] #536 Updated azure-regions.json with new regions 

# Issues 

- [ ] #537 🎯2024-07-02 Carbon Aware SDK Weekly Meeting Agenda 

- [ ] #534 🎯2024-06-25 Carbon Aware SDK Weekly Meeting Agenda
- [ ] #510 Gap Analysis for WattTime v3

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by nttDamien** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by danuw** [comment]
- [ ] #540
- [ ]

**Comment by danuw** [comment]
Attended

**Comment by vaughanknight** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended
