### ISSUE TITLE
🎯2024-07-16 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#542]
## Date
2024-07-16 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
    - [x] #540
    - [x] Prioritised PRs:
       - [x] #538 
       - [x] #524  
       - [x] #366
- [x] Discuss Issues

# PRs
PRs Updated:

- [x] #541 Update CHANGELOG.md for v1.5 
- [x] #538 1.5 Release WattTime v3  
- [x] #524 Add blog article for .NET 8 upgrade 
- [ ] #366 Implement Data Source Registration per ADR-0006 

PRs Closed:

# Issues 

Issues Updated:

- [ ] #540 Create Release Notes for 1.5 
- [ ] #539 🎯 2024-07-09 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #520 [Bug]: Clean up DCO issues  
- [ ] #396 [Feature Contribution]: Better to throw exception when future datetime is specified to endpoints for current/historical data 
- [ ] #272 Feature request: Publish a versioned release as a NuGet package of the Carbon Aware SDK 

Issues Closed:

- [ ] #537 🎯2024-07-02 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #535 [Bug]: Configuration for locations loads twice  
- [ ] #443 [Feature Contribution]: Add support for WattTime v3 - latest version of the API with new features and coverage 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by danuw** [comment]
- [ ] Next release for Sept ? What should be included?
- [ ] #540
- [ ] Prioritised PRs:
   - [ ] #538 
   - [ ] #524  
   - [ ] #366
- [ ] @YaSuenag believes we should not need an ADR https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/528. Suggestion:
   - [ ] Create a troubleshooting section in the docs + env variables for the helm chart - @YaSuenag to create a PR 
- [ ] Created milestone for 1.6
- [ ] created 1.6 tag and started adding the tag https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aissue+label%3Av1.6+
- [x] can NTT guys edit the project page kanban page https://github.com/orgs/Green-Software-Foundation/projects/15/views/2?filterQuery=
