### ISSUE TITLE
🎯2024-07-23 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#546]
## Date
2024-07-23 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [ ] Review Pull Requests
   - [ ] 1.5
   - [ ] #544 
- [ ] Discuss Issues

# PRs

PRs Updated:

- [ ] #544 Add env directive to values.yaml and troubleshooting guide to avoid inotify limitation on Linux 
- [ ] #538 1.5 Release WattTime v3  

PRs Closed:

- [ ] #541 Update CHANGELOG.md for v1.5 

# Issues 

Issues Updated:

- [ ] #545 [Bug]: Unable to include Helm chart to build on top of it 
- [ ] #542 🎯2024-07-16 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #528 [Bug]: Avoid inotify limit in WebAPI container on Kubernetes 
- [ ] #272 Feature request: Publish a versioned release as a NuGet package of the Carbon Aware SDK 

Issues Closed:

- [ ] #543 test by yasumasa 
- [ ] #540 Create Release Notes for 1.5 
- [ ] #539 🎯 2024-07-09 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #455 ADR for Prometheus Metrics end point 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by tiwatsuka** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by nttDamien** [comment]
Attended
