### ISSUE TITLE
🎯2024-07-30 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#549]
## Date
2024-07-30 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [ ] Convene & Roll Call (5mins)
- [ ] Review Meeting Notices (see above)
- [ ] Review the agenda and suggest new agenda points
- [ ] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs

PRs Updated:

PRs Closed:

- [ ] #547 1.5 WattTime v3 Updates 
- [ ] #538 1.5 Release WattTime v3  
- [ ] #523 documentation-change.yml: Created issue template for documentation ch… 

# Issues 

Issues Updated:

- [ ] #546 🎯2024-07-23 Carbon Aware SDK Weekly Meeting Agenda 

Issues Closed:

- [ ] #548 [Bug]: Carbon Aware API test endpoint needs updating to match new release 
- [ ] #545 [Bug]: Unable to include Helm chart to build on top of it 
- [ ] #542 🎯2024-07-16 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #509 Create issue template type for documentation updates 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
Meeting was cancelled and will be covered in today's (following week's meeting)
