### ISSUE TITLE
🎯2024-08-20 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#554]
## Date
2024-08-20 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes

    - [x] .net 8 blog PR finalised
    - [ ] Roadmap
    
    To focus on next:
    - [ ] #366
    
    Provisional topics to discuss at next session on next focus:
    - Samples?
    - Packages?
    - Geo location?
    - New content?
    - Clean up active PRs and triage issues?
    - Get full list to ensure we are going in the right direction
  
- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs

PRs Updated:

PRs Closed:

- [x] #553 Documentation: "it's" is used incorrectly several times 
- [x] #551 Docs/blog update for releases 1.3 to1.5 and fix 
- [x] #524 Add blog article for .NET 8 upgrade 

# Issues 

Issues Updated:

- [x] #550 🎯2024-08-06 Carbon Aware SDK Weekly Meeting Agenda 
- [x] #501 .NET8 blog article 

Issues Closed:

- [x] #552 Documentation: "it's" is used incorrectly several times 
- [x] #549 🎯2024-07-30 Carbon Aware SDK Weekly Meeting Agenda 
- [x] #546 🎯2024-07-23 Carbon Aware SDK Weekly Meeting Agenda 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by YaSuenag** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by danuw** [comment]
Thank you all 
Some notes:

- [ ] .net 8 blog post published at https://carbon-aware-sdk.greensoftware.foundation/blog/dotnet-8-upgrade and  https://greensoftware.foundation/articles/upgrading-to-net-8-inside-the-carbon-aware-sdk-v1-4
- [ ] Next provisional release date set to Sept 10th? Can we get any or all of the open PRs into it? Ideally by order of priority we would cover the following
  - [ ] #544 
  - [ ] #531 
  - [ ] #471 
  - [ ] #450 
  - [ ] #366

**Comment by YaSuenag** [comment]
I've filed new PR: #555 

It is high priority for us, so I hope it is merged ASAP - by next release at least.
I want to get next version by mid of Sept.

**Comment by YaSuenag** [comment]
@vaughanknight @danuw CC: @danuw 
IMO following order is good to apply for next release (in Sept)

1. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/555
2. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/544
3. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/531
4. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/450
    * Need to resolve confliction
5. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/366
    * Need to resolve confliction
6. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/471
