### ISSUE TITLE
🎯 2024-08-27 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#556]
## Date
2024-08-27 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [ ] Review Pull Requests

1. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/555
2. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/544
3. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/531
4. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/450
    * Need to resolve confliction
5. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/366
    * Need to resolve confliction
6. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/471

- [ ] Discuss Issues

# PRs

PRs Updated:

- [ ] #555 Add a configuration for disabling to cache JSON emission data 
- [ ] #450 Remove JSON examples from artifacts 

PRs Closed:

# Issues 

Issues Updated:

- [ ] #554 🎯2024-08-20 Carbon Aware SDK Weekly Meeting Agenda 

Issues Closed:

- [ ] #550 🎯2024-08-06 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #501 .NET8 blog article 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by vaughanknight** [comment]
Discussed:  @vaughanknight will look at #366 and look at how we can incorporate it into current work, whether refactor for conflicts, or reimplement separately.
