### ISSUE TITLE
🎯2024-09-03 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#557]
## Date
2024-09-03 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues
- [ ] Today:
   - [x] Trigger Helm charts
   - [x] #531 - @vaughanknight to provide the final check following last week's review
   - [x] Roadmap - next release?

# PRs
PRs Updated:

- [x] #531 Add configuration for tracing log 
- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 
- [ ] #450 Remove JSON examples from artifacts 
- [x] #366 Implement Data Source Registration per ADR-0006 

PRs Closed:

- [ ] #555 Add a configuration for disabling to cache JSON emission data 
- [ ] #544 Add env directive to values.yaml and troubleshooting guide to avoid inotify limitation on Linux 

# Issues 

Issues Updated:

- [ ] #556 🎯 2024-08-27 Carbon Aware SDK Weekly Meeting Agenda 
- [x] #508 Case-study submission - Microsoft 
- [x] #445 [Bug]: Investigate codecov for the carbon-aware-sdk repo 
- [x] #179 [Feature Contribution]: Geocode support in the API 

Issues Closed:

- [ ] #554 🎯2024-08-20 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #528 [Bug]: Avoid inotify limit in WebAPI container on Kubernetes 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by nttDamien** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by danuw** [comment]
- [ ] Helm chart triggered https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions/runs/10678237170 - cc @YaSuenag 
- [ ] @vaughanknight , any news on #366 and #531 please?
- [ ] Reminder that next release is expected next week or following so will start to create the changelog (@danuw )

**Comment by YaSuenag** [comment]
Thank you for publishing new Hem chart!!
