### ISSUE TITLE
🎯2024-09-10 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#558]
## Date
2024-09-10 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [ ] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

Release to include the following items (where closed) : https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=label%3Av1.6+

Milestone: https://github.com/Green-Software-Foundation/carbon-aware-sdk/milestone/8

# PRs

# Issues 

Issues Updated:

- [ ] #557 🎯2024-09-03 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #508 Case-study submission - Microsoft 
- [ ] #445 [Bug]: Investigate codecov for the carbon-aware-sdk repo 
- [ ] #440 [Feature Contribution]: Remove JSON examples from WebAPI container 
- [ ] #179 [Feature Contribution]: Geocode support in the API 

Issues Closed:

- [ ] #556 🎯 2024-08-27 Carbon Aware SDK Weekly Meeting Agenda 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by YaSuenag** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by danuw** [comment]
Release notes for 1.6 created and ready to be merged to create new release cc @vaughanknight 
https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/560
