### ISSUE TITLE
🎯 2024-09-17 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#561]
## Date
2024-09-17 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
   - [ ] Release 1.6
- [x] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs
PRs Updated:

- [ ] #560 Update CHANGELOG.md for 1.6 
- [ ] #531 Add configuration for tracing log 
- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 
- [ ] #450 Remove JSON examples from artifacts 
- [ ] #366 Implement Data Source Registration per ADR-0006 

PRs Closed:

# Issues 

Issues Updated:

- [ ] #559 Create Release Notes for 1.6 
- [ ] #558 🎯2024-09-10 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #272 Feature request: Publish a versioned release as a NuGet package of the Carbon Aware SDK 

Issues Closed:

- [ ] #557 🎯2024-09-03 Carbon Aware SDK Weekly Meeting Agenda 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by YaSuenag** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by danuw** [comment]
(comment was not posted so posting now)

Main had discrepencies with dev we could not understand so we created a PR to bring together / realign https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/562 before we proceed to the release https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/563
