### ISSUE TITLE
🎯 2024-09-24 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#567]
## Date
2024-09-24 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [ ] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs

PRs Updated:

- [ ] #565 Upgrade actions/{upload,download}-artifact 
- [ ] #563 Release 1.6 - fixes and minor changes 

PRs Closed:

- [ ] #562 Hotfix/discrepency main dev fix 
- [ ] #560 Update CHANGELOG.md for 1.6 

# Issues 

Issues Updated:

- [ ] #567 🎯 2024-09-24 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #566 [Bug]: WattTime as Data Source results in 403 Forbidden 
- [ ] #564 [Bug]: 1-pr.yaml should upgrade actions/upload-artifact 
- [ ] #561 🎯 2024-09-17 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #348 [Feature Contribution]: Implement Data Source Registration per ADR-0006 

Issues Closed:

- [ ] #559 Create Release Notes for 1.6 
- [ ] #558 🎯2024-09-10 Carbon Aware SDK Weekly Meeting Agenda 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
hello - running a bit late this morning - should be 5-10 min late

**Comment by danuw** [comment]
Release pending this PR being fixed https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/568

**Comment by danuw** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended
