### ISSUE TITLE
🎯2024-10-08 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#574]
## Date
2024-10-08 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
  - [ ] #570 & #571
  - [x] IF plugin 
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues

# PRs

PRs Updated:

- [x] #572 EM datasource didn't filter out-of-range emission data 
- [x] #563 Release 1.6 - fixes and minor changes 

PRs Closed:

- [x] #569 Update CarbonAwareController.cs (minor typos) 
- [x] #568 Docs fixes and release notes post for 1.6 
- [x] #565 Upgrade actions/{upload,download}-artifact 

# Issues 

Issues Updated:

- [ ] #573 Documentation: WattTime provides marginal while Electricity Map provides average signal 
- [ ] #571 [Bug]: Cannot get the value of a token type 'Null' as a number 
- [ ] #570 [Bug]:  webapi query on bylocation shows 24 hours worth of data even when smaller range requested 
- [ ] #567 🎯 2024-09-24 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #525 Define our 'value add' in our documentation 
- [ ] #426 [Bug]: Unhandled exception. CarbonAware.Exceptions.ConfigurationException: No data sources are configured 

Issues Closed:

- [ ] #566 [Bug]: WattTime as Data Source results in 403 Forbidden 
- [ ] #564 [Bug]: 1-pr.yaml should upgrade actions/upload-artifact 
- [ ] #561 🎯 2024-09-17 Carbon Aware SDK Weekly Meeting Agenda 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by danuw** [comment]
Thank you all, great meeting today and some exciting changes coming ahead...

Congrats on the latest release ... https://github.com/Green-Software-Foundation/carbon-aware-sdk/releases/tag/v1.6.0

So, latest priority:
- Review PRs:
   - #570 ( #572)
   - #571  for which @YaSuenag will create a PR
   - #366 
   - #531 
   - #450 
   - #471
-

**Comment by tiwatsuka** [comment]
Attended

**Comment by YaSuenag** [comment]
> https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/571 for which @YaSuenag will create a PR

I've created: #575
