### ISSUE TITLE
🎯 2024-10-15 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#576]
## Date
2024-10-15 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [ ] Convene & Roll Call (5mins)
- [ ] Review Meeting Notices (see above)
- [ ] Review the agenda and suggest new agenda points
- [ ] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs

PRs Updated:

- [ ] #531 Add configuration for tracing log 
- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 
- [ ] #450 Remove JSON examples from artifacts 
- [ ] #366 Implement Data Source Registration per ADR-0006 

PRs Closed:

- [ ] #575 Consider null value in carbonIntensity on EM 
- [ ] #572 EM datasource didn't filter out-of-range emission data 
- [ ] #563 Release 1.6 - fixes and minor changes 

# Issues 

Issues Updated:

- [ ] #574 🎯2024-10-08 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #272 Feature request: Publish a versioned release as a NuGet package of the Carbon Aware SDK 

Issues Closed:

- [ ] #571 [Bug]: Cannot get the value of a token type 'Null' as a number 
- [ ] #570 [Bug]:  webapi query on bylocation shows 24 hours worth of data even when smaller range requested 
- [ ] #567 🎯 2024-09-24 Carbon Aware SDK Weekly Meeting Agenda 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**
