### ISSUE TITLE
🎯2024-10-22 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#577]
## Date
2024-10-22 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
   - [x] minor release for https://github.com/Green-Software-Foundation/carbon-aware-sdk/pulls?q=is%3Apr+is%3Aclosed+label%3Av1.6.1
   - [x] open pull requests
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues

# PRs
PRs Updated:

- [x] #531 Add configuration for tracing log 
- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 
- [ ] #450 Remove JSON examples from artifacts 
- [ ] #366 Implement Data Source Registration per ADR-0006 

PRs Closed:

- [x] #575 Consider null value in carbonIntensity on EM 
- [x] #572 EM datasource didn't filter out-of-range emission data 
- [x] #563 Release 1.6 - fixes and minor changes 

# Issues 

Issues Updated:

- [x] #574 🎯2024-10-08 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #272 Feature request: Publish a versioned release as a NuGet package of the Carbon Aware SDK 

Issues Closed:

- [ ] #576 🎯 2024-10-15 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #571 [Bug]: Cannot get the value of a token type 'Null' as a number 
- [ ] #570 [Bug]:  webapi query on bylocation shows 24 hours worth of data even when smaller range requested 
- [ ] #567 🎯 2024-09-24 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #525 Define our 'value add' in our documentation 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
Agenda ready - sorry I can't attend today

**Comment by YaSuenag** [comment]
I cannot attend today too.  
I want to get review of #531 . Also I want to move forward #471 if CASDK IF plugin (by Dan) can use  NPM module generated by OpenAPI doc of WebAPI.

**Comment by vaughanknight** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by vaughanknight** [comment]
@YaSuenag - We will look to review #531 this week, and it can go in a 1.6.2 release next week if approved.  1.6.1 release will still go out this week as it's already all approved and merged (and we don't want to create a dependency just in case)

**Comment by YaSuenag** [comment]
@vaughanknight 
Do you have target date of 1.6.1 release? I will show demonstration of CASDK in [Open Source Conference in Tokyo, Japan](https://event.ospn.jp/osc2024-fall/) in this Saturday. So I'm happy if 1.6.1 is available by that event.
