### ISSUE TITLE
🎯2024-11-19 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#589]
## Date
YYYY-MM-DD - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
   - [ ] current PRs
   - [ ] #471 
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [ ] Discuss Issues

# PRs
PRs Updated:

- [ ] #588 Add gh cli to devcontainer/codespace 
- [ ] #471 Add GHA workflow for generating WebAPI client library for Java 

PRs Closed:

- [ ] #587 Release 1.6.1 
- [ ] #586 Hotfix/1.6.1 merge issues 
- [ ] #583 Release 1.6.1

# Issues 

Issues Updated:

- [ ] #585 🎯2024-11-12 Carbon Aware SDK Weekly Meeting Agenda 

Issues Closed:

- [ ] #584 [Bug]: Discrepancy between main and dev leads to merge conflicts 
- [ ] #581 🎯2024-11-05 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #502 Finalise Impact Framework Plug-In 
- [ ] #476 [Feature Contribution]: Automatically remove "Ready for review" label on closed PRs or Issues

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by nttDamien** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by danuw** [comment]
- [ ] Java client library package generator merged
   - [ ] @YaSuenag to create issue and PR for NPM packages as sampled here https://github.com/YaSuenag/ts-npm-casdk-sandbox/blob/main/.github/workflows/generate-npm-lib.yaml
- [ ] Next, @vaughanknight shall we start looking at .net 9, aspire and dapr?

**Comment by YaSuenag** [comment]
> @YaSuenag to create issue and PR for NPM packages as sampled here https://github.com/YaSuenag/ts-npm-casdk-sandbox/blob/main/.github/workflows/generate-npm-lib.yaml

Added: #590

**Comment by YaSuenag** [comment]
I've sent new PR for adding workflow to generate WebAPI client library for NPM: #591
