### ISSUE TITLE
🎯2024-12-17 Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#598]
## Date
2024-12-17 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs

PRs Updated:

- [ ] #597 Add Client API documents for WebAPI 1.0.0 
- [ ] #450 Remove JSON examples from artifacts

PRs Closed:

- [ ] #591 Publish WebAPI client library for NPM 

Issues Updated:

- [ ] #598 🎯2024-12-17 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #596 [Feature Contribution]: Incorporate Code Rabbit to the repo for PR review assistance 
- [ ] #595 [Feature Contribution]: Upgrade to .net 9 
- [ ] #594 🎯2024-12-10 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #520 [Bug]: Clean up DCO issues  

Issues Closed:

- [ ] #593 🎯2024-12-03 Carbon Aware SDK Weekly Meeting Agenda 
- [ ] #590 [Feature Contribution]: Publish WebAPI client library for NPM 
- [ ] #508 Case-study submission - Microsoft 
- [ ] #446 [Bug]: Address Security alerts

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by danuw** [comment]
API clients library merged and tested - all working well with the exception of the DCO (#599) to try and incorporate in future changes.

To cover next: https://github.com/danuw/if-casdk-plugin/pull/4

_We will pause these meetings for the next 2 weeks. Expected to resume on the Tuesday 7th of Jan 2025._

cc @vaughanknight

**Comment by danuw** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended
